/* ================================================================
   WorkflowPro - EmployeeDB
   Phase 2 - Seed data script
   Run after 01_CreateSchema.sql
   ================================================================ */

USE EmployeeDB;
GO

/* ---------------------------------------------------------------
   Departments
   --------------------------------------------------------------- */
INSERT INTO dbo.Departments (Name, Code, Description, IsActive)
VALUES
    ('Administration', 'ADMIN', 'System administration and management', 1),
    ('Human Resources', 'HR',    'Recruitment, payroll and employee welfare', 1),
    ('Engineering',     'ENG',   'Software development and DevOps', 1),
    ('Finance',         'FIN',   'Accounts and financial planning', 1);
GO

/* ---------------------------------------------------------------
   Default Employee record for the system administrator
   --------------------------------------------------------------- */
INSERT INTO dbo.Employees
    (EmployeeCode, FirstName, LastName, Email, Phone, DepartmentId,
     Designation, DateOfJoining, Gender, IsActive)
VALUES
    ('EMP-0001', 'System', 'Administrator', 'admin@workflowpro.local', NULL,
     (SELECT DepartmentId FROM dbo.Departments WHERE Code = 'ADMIN'),
     'System Administrator', GETDATE(), 'Other', 1);
GO

/* ---------------------------------------------------------------
   Default admin login.
   NOTE: PasswordHash/PasswordSalt below are PLACEHOLDERS.
   Real values are generated by the Authentication module (Phase 3)
   using PBKDF2/HMACSHA256 with a per-user salt. Do not go live with
   these values — reset via the seeding utility once Phase 3 lands.
   Default credentials for local dev only: admin / Admin@123
   --------------------------------------------------------------- */
INSERT INTO dbo.Users
    (Username, Email, PasswordHash, PasswordSalt, Role, EmployeeId, IsActive)
VALUES
    ('admin', 'admin@workflowpro.local',
     'PLACEHOLDER_HASH_REGENERATE_IN_PHASE3',
     'PLACEHOLDER_SALT_REGENERATE_IN_PHASE3',
     'Admin',
     (SELECT EmployeeId FROM dbo.Employees WHERE EmployeeCode = 'EMP-0001'),
     1);
GO
